name: 'Docker Build and Push'
description: 'Build Docker image and push to ECR'

inputs:
  component:
    description: 'Component to build (backend or frontend)'
    required: true
  environment:
    description: 'Environment (local or prod)'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  ecr-registry:
    description: 'ECR registry URL'
    required: true
  push:
    description: 'Whether to push the image'
    required: false
    default: 'true'

outputs:
  image-tag:
    description: 'Docker image tag'
    value: ${{ steps.meta.outputs.tags }}
  image-digest:
    description: 'Docker image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.ecr-registry }}/lian-date-${{ inputs.environment }}-${{ inputs.component }}
        tags: |
          type=sha,prefix={{branch}}-
          type=raw,value=latest
          type=semver,pattern={{version}}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ./${{ inputs.component }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

    - name: Image summary
      shell: bash
      run: |
        echo "### Docker Image Built ðŸ³" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Component:** ${{ inputs.component }}" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tags:**" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "**Digest:** ${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
