name: 'Build and Test'
description: 'Build and test application (Backend or Frontend)'

inputs:
  component:
    description: 'Component to build and test (backend or frontend)'
    required: true
  java-version:
    description: 'Java version for backend'
    required: false
    default: '21'
  node-version:
    description: 'Node.js version for frontend'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Build and Test Backend
      if: inputs.component == 'backend'
      shell: bash
      run: |
        cd backend
        chmod +x gradlew
        ./gradlew clean build test --no-daemon

    - name: Setup Java for Backend
      if: inputs.component == 'backend'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build and Test Frontend
      if: inputs.component == 'frontend'
      shell: bash
      run: |
        cd frontend
        npm ci
        npm run lint
        npm test -- --coverage
        npm run build

    - name: Setup Node.js for Frontend
      if: inputs.component == 'frontend'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ inputs.component }}
        path: |
          backend/build/test-results/**/*.xml
          frontend/coverage/
        retention-days: 7
